# The Travis setup:
# - run testsuite for every PHP version
language: php
php:
  - '7.1'
  - '7.0'
  - '5.6'
  - hhvm
install:
  - composer update --profile --verbose
after_success:
  - bash <(curl -s https://codecov.io/bash)
